import { Info } from "lucide-react";
import { PageHeader } from "@/components/layout/page-header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Storyboard } from "@/components/media/storyboard";
import { MediaStudio } from "@/components/media/media-studio";
import { getAllSignals, listAllPredictionMarkets } from "@/lib/data";
import { buildDailyMarketBriefing, higgsfield } from "@/lib/integrations/higgsfield";

export const dynamic = "force-dynamic";
export const metadata = { title: "Briefings" };

export default async function BriefingsPage() {
  const [signals, movers] = await Promise.all([getAllSignals(), listAllPredictionMarkets()]);
  const topMovers = [...movers].sort((a, b) => Math.abs(b.changePct) - Math.abs(a.changePct));
  const briefing = buildDailyMarketBriefing(signals, topMovers);
  const status = higgsfield.status();
  const topSignal = [...signals].sort((a, b) => b.confidence - a.confidence)[0];

  return (
    <>
      <PageHeader
        title="AI Briefings & Media"
        subtitle="Higgsfield turns finished signals into market briefings, explainers, and social clips."
      />

      <div className="flex items-start gap-2 rounded-lg border border-border bg-muted/30 px-3 py-2 text-xs text-muted-foreground">
        <Info className="mt-0.5 size-3.5 shrink-0 text-primary" />
        <p>
          {status.note} Storyboards are generated by Apex from real signal data; Higgsfield renders
          them to video. Higgsfield never performs market calculations.
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="text-sm">Today&apos;s 60-second market briefing</CardTitle>
        </CardHeader>
        <CardContent>
          <Storyboard brief={briefing} stub={!status.connected} />
        </CardContent>
      </Card>

      <MediaStudio defaultSymbol={topSignal?.asset.symbol ?? "BTC"} />
    </>
  );
}
